### ISSUE TITLE
[BUG]Hello Author, I put you this plug-in into the plug-in folder, plug-in configuration out, but my input instructions are not useful

### ISSUE THREAD

**Issue by 1097838154** [Nuckerr/KitPvPPlus#10]
**1.** Hello Author, I put you this plug-in into the plug-in folder, plug-in configuration out, but my input instructions are not useful
**2.** Describe how it should function
**3.** 1.0.0
**4.**1.12.2
**5.** spigot
**6.** ![SN @UTZKXNOH4RWBGG`MKYI](https://user-images.githubusercontent.com/89739853/131255958-cc9e4e00-db7d-483d-bd82-cc8e079fe272.png)

**Comment by Nuckerr** [comment]
Fixed with release `1.0.1`
